import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                primary: '#bec6e0',
                'surface-container': '#152031',
                'inverse-primary': '#565e74',
                'primary-container': '#0f172a',
                'inverse-on-surface': '#263143',
                'primary-fixed-dim': '#bec6e0',
                error: '#ffb4ab',
                'on-surface-variant': '#c6c6cd',
                'inverse-surface': '#d8e3fb',
                'on-error': '#690005',
                background: '#081425',
                'surface-container-high': '#1f2a3c',
                'on-primary-container': '#798098',
                tertiary: '#f9bd22',
                'on-primary-fixed': '#131b2e',
                'on-background': '#d8e3fb',
                'surface-dim': '#081425',
                'surface-container-low': '#111c2d',
                'surface-variant': '#2a3548',
                'on-tertiary-container': '#a47a00',
                surface: '#081425',
                'error-container': '#93000a',
                'on-tertiary-fixed': '#261a00',
                'surface-container-lowest': '#040e1f',
                'on-error-container': '#ffdad6',
                'on-secondary-fixed': '#001f25',
                'on-secondary': '#00363e',
                'on-secondary-container': '#00515d',
                'secondary-fixed': '#a2eeff',
                'on-primary-fixed-variant': '#3f465c',
                'secondary-fixed-dim': '#2fd9f4',
                'secondary-container': '#00cbe6',
                'tertiary-fixed-dim': '#f9bd22',
                'on-primary': '#283044',
                'surface-container-highest': '#2a3548',
                'tertiary-container': '#211600',
                outline: '#909097',
                'surface-tint': '#bec6e0',
                'primary-fixed': '#dae2fd',
                secondary: '#5de6ff',
                'outline-variant': '#45464d',
                'tertiary-fixed': '#ffdf9f',
                'on-tertiary-fixed-variant': '#5c4300',
                'on-secondary-fixed-variant': '#004e5a',
                'on-surface': '#d8e3fb',
                'on-tertiary': '#402d00',
                'surface-bright': '#2f3a4c',

                // Legacy & helper mappings
                brand: {
                    50: '#effefb',
                    100: '#c8fff3',
                    300: '#5de6ff',
                    400: '#2fd9f4',
                    500: '#00cbe6',
                    600: '#009bb0',
                    700: '#006c7c',
                    800: '#00515d',
                    900: '#00363e',
                    950: '#001f25',
                },
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Plus Jakarta Sans', 'sans-serif'],
                label: ['Geist', 'sans-serif'],
                mono: ['Geist', ...defaultTheme.fontFamily.mono],
            },
            spacing: {
                unit: '4px',
                'margin-mobile': '20px',
                'container-max': '1280px',
                gutter: '16px',
                'margin-desktop': '48px',
            },
            boxShadow: {
                glow: '0 0 16px rgba(93, 230, 255, 0.2)',
                'glow-lg': '0 0 24px rgba(93, 230, 255, 0.35)',
                'glow-gold': '0 0 16px rgba(249, 189, 34, 0.3)',
                'glass-card': '0 0 16px rgba(190, 198, 224, 0.05)',
            },
            animation: {
                'fade-in': 'fadeIn 0.4s ease-out',
                'fade-in-up': 'fadeInUp 0.4s ease-out',
                'pulse-glow': 'pulseGlow 2.5s infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeInUp: {
                    '0%': { opacity: '0', transform: 'translateY(12px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                pulseGlow: {
                    '0%, 100%': { opacity: '1', boxShadow: '0 0 16px rgba(93, 230, 255, 0.2)' },
                    '50%': { opacity: '0.8', boxShadow: '0 0 24px rgba(93, 230, 255, 0.4)' },
                },
            },
        },
    },

    plugins: [forms],
};
